services:
  frontend:
    image: code_execution_frontend
    build:
      context: ./frontend/code-execution-frontend
    ports:
      - 8080:3000
    depends_on:
      - backend_api

  backend_api:
    image: code_execution_api
    ports:
      - 8000:8000
    build:
      context: ./backend/code-execution-engine-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - test1:/test1

volumes:
  test1:
